image: node

variables:
  SELENIUM_HUB_HOST: "localhost"

stages:
  - start-selenoid
  - test

start-selenoid:
  stage: start-selenoid
  script: echo "download cm and start selenoid"

test:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - npm i
    - npm t

