image: node:14.15.5-alpine3.10

variables:
  SELENIUM_HUB_HOST: "localhost"
#  SELENIUM_HUB_HOST: "selenium__standalone-chrome"

stages:
  - test
  - report

# investigate how to start selenoid instead of selenium-chrome
#start-selenoid:
#  stage: start-selenoid
#  script:
#    - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start
#    - curl http://localhost:4444/status

cache:
  paths:
    - node_modules/
    - allure-results/

test:
  stage: test
  services:
    - selenium/standalone-chrome
  before_script:
    - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start
    - curl http://localhost:4444/status
  script:
    - npm cit

report:
  stage: report
  script:
    - apk add openjdk11
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    - export JAVA_HOME
    - npm run report:generate
  artifacts:
    expire_in: 30 days
    paths:
      - allure-report
  when: always
